//
// Created by egor on 2/24/24.
//

#include <iostream>
#include <fstream>

#include "writer.h"

void dump_necks(std::string const & dir, size_t count, std::vector<Eigen::Vector3d> const & x,
                std::vector<bool> const & bonded_contacts, double r_part) {

    std::stringstream out_file_name;
    out_file_name << dir << "/necks_" << count << ".vtk";
    std::ofstream ofs(out_file_name.str());

    if (!ofs.good()) {
        std::cerr << "Unable to create a dump file at " << out_file_name.str() << std::endl;
        exit(EXIT_FAILURE);
    }

    size_t neck_count = std::count(bonded_contacts.begin(), bonded_contacts.end(), true) / 2u;

    ofs << "# vtk DataFile Version 4.0" << "\n";
    ofs << "Generated by libgran" << "\n";
    ofs << "ASCII" << "\n";
    ofs << "DATASET POLYDATA" << "\n";
    ofs << "POINTS " << neck_count << " FLOAT" << "\n";

    for (size_t i = 0; i < x.size() - 1; i ++) {
        for (size_t j = i + 1; j < x.size(); j ++) {
            if (!bonded_contacts[i * x.size() + j])
                continue;

            // This is a bonded contact
            Eigen::Vector3d position = (x[j] + x[i]) / 2.0 / r_part; // Compute the position

            ofs << position[0] << " " << position[1] << " " << position[2] << " ";
        }
    }

    ofs << "\n" << "\n";
    ofs << "POINT_DATA " << neck_count << "\n";
    ofs << "FIELD FieldData 1" << "\n";
    ofs << "normals 3 " << neck_count << " double" << "\n";
    for (size_t i = 0; i < x.size() - 1; i ++) {
        for (size_t j = i + 1; j < x.size(); j ++) {
            if (!bonded_contacts[i * x.size() + j])
                continue;

            // This is a bonded contact
            Eigen::Vector3d orientation = (x[j] - x[i]).normalized(); // Compute the orientation vector

            ofs << orientation[0] << " " << orientation[1] << " " << orientation[2] << " ";
        }
    }
}

void dump_particles(std::string const & dir, size_t count, std::vector<Eigen::Vector3d> const & x,
                    std::vector<Eigen::Vector3d> const & v,
                    std::vector<Eigen::Vector3d> const & a,
                    std::vector<Eigen::Vector3d> const & omega,
                    std::vector<Eigen::Vector3d> const & alpha,
                    double r_part) {
    std::stringstream out_file_name;
    out_file_name << dir << "/particles_" << count << ".vtk";
    std::ofstream ofs(out_file_name.str());

    if (!ofs.good()) {
        std::cerr << "Unable to create a dump file at " << out_file_name.str() << std::endl;
        exit(EXIT_FAILURE);
    }

    ofs << "# vtk DataFile Version 4.0" << "\n";
    ofs << "Generated by libFractalCommon" << "\n";
    ofs << "ASCII" << "\n";
    ofs << "DATASET POLYDATA" << "\n";
    ofs << "POINTS " << x.size() << " FLOAT" << "\n";

    // Coordinates are normalized to avoid issues with ParaView and small particles
    for (auto const & p : x) {
        ofs << p[0] / r_part << " " << p[1] / r_part << " " << p[2] / r_part << " ";
    }

    ofs << "\n\n";
    ofs << "POINT_DATA " << x.size() << "\n";
    ofs << "FIELD FieldData 4" << "\n";
    ofs << "v 1 " << x.size() << " double\n";
    for (auto const & p : v) {
        ofs << p.norm() << " ";
    }
    ofs << "\n";
    ofs << "a 1 " << x.size() << " double\n";
    for (auto const & p : a) {
        ofs << p.norm() << " ";
    }
    ofs << "\n";
    ofs << "omega 1 " << x.size() << " double\n";
    for (auto const & p : omega) {
        ofs << p.norm() << " ";
    }
    ofs << "\n";
    ofs << "alpha 1 " << x.size() << " double\n";
    for (auto const & p : alpha) {
        ofs << p.norm() << " ";
    }
    ofs << "\n";
}
