name: Build, Test, Deploy

run-name: ${{ github.actor }} triggered pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AFS_DEPLOY_PASS: ${{ secrets.AFS_DEPLOY_PASS }}

jobs:
  Compile-Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          mkdir result
          mkdir cmake-build
          cd cmake-build
          cmake ..
          cmake --build . --config Release
          move ./Release/aggregate_deposition.exe ../result/
      - name: Archive compiled artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64
          path: |
            result

  Compile-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          mkdir result
          mkdir cmake-build
          cd cmake-build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
          strip aggregate_deposition
          mv ./aggregate_deposition ../result/
          cd ..
          tar -czvf linux-x86_64.tar.gz result
          sshpass -p ${{ env.AFS_DEPLOY_PASS }} scp -o StrictHostKeyChecking=no linux-x86_64.tar.gz ed242@afsconnect1.njit.edu:~/public_html/soot-dem-binaries
      - name: Archive compiled artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64
          path: |
            result