name: Build, Test, Deploy

run-name: CI pipeline triggered by ${{ github.actor }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#  Compile-Linux-ICC:
#    runs-on: ubuntu-latest
#    container: intel/oneapi-basekit
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#        with:
#          submodules: recursive
#      - name: Build
#        run: |
#          mkdir dist/soot-dem/bin
#          mkdir cmake-build
#          cd cmake-build
#          export CC=icx
#          export CXX=icpx
#          cmake -DCMAKE_BUILD_TYPE=Release ..
#          cmake --build .
#          strip aggregate_deposition
#          strip afm_necking_fraction
#          strip restructuring
#          mv ./aggregate_deposition ../dist/soot-dem/bin/
#          mv ./afm_necking_fraction ../dist/soot-dem/bin/
#          mv ./restructuring ../dist/soot-dem/bin/
#      - name: Archive compiled artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: soot-dem-linux-icc-x86_64
#          path: |
#            dist

  Compile-Windows-Clang:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          mkdir dist/soot-dem/bin
          mkdir cmake-build
          cd cmake-build
          choco install ninja
          $Env:CC="clang"
          $Env:CXX="clang++"
          cmake -DCMAKE_BUILD_TYPE=Release -G Ninja ..
          cmake --build .
          move ./aggregate_deposition.exe ../dist/soot-dem/bin/
          move ./afm_necking_fraction.exe ../dist/soot-dem/bin/
          move ./restructuring.exe ../dist/soot-dem/bin/
      - name: Archive compiled artifact
        uses: actions/upload-artifact@v3
        with:
          name: soot-dem-windows-clang-x86_64
          path: |
            dist
            
  Compile-Windows-MSVC:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          mkdir dist/soot-dem/bin
          mkdir cmake-build
          cd cmake-build
          cmake ..
          cmake --build . --config Release
          move ./Release/aggregate_deposition.exe ../dist/soot-dem/bin/
          move ./Release/afm_necking_fraction.exe ../dist/soot-dem/bin/
          move ./Release/restructuring.exe ../dist/soot-dem/bin/
      - name: Archive compiled artifact
        uses: actions/upload-artifact@v3
        with:
          name: soot-dem-windows-msvc-x86_64
          path: |
            dist

#  Compile-Windows-MinGW:
#    runs-on: windows-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#        with:
#          submodules: recursive
#      - name: Set up MinGW
#        uses: egor-tensin/setup-mingw@v2.2.0
#        with:
#          version: 12.2.0
#          platform: x64
#      - name: Build
#        run: |
#          where gcc
#          mkdir bin
#          mkdir cmake-build
#          cd cmake-build
#          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR="MinGW Makefiles" ..
#          cmake --build .
#          strip aggregate_deposition.exe
#          strip afm_necking_fraction.exe
#          strip restructuring.exe
#          move ./aggregate_deposition.exe ../bin/
#          move ./afm_necking_fraction.exe ../bin/
#          move ./restructuring.exe ../bin/
#      - name: Archive compiled artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: soot-dem-windows-MinGW-x86_64
#          path: |
#            bin

  Compile-Linux-GNU:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          mkdir dist/soot-dem/bin
          mkdir cmake-build
          cd cmake-build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
          strip aggregate_deposition
          strip afm_necking_fraction
          strip restructuring
          mv ./aggregate_deposition ../dist/soot-dem/bin/
          mv ./afm_necking_fraction ../dist/soot-dem/bin/
          mv ./restructuring ../dist/soot-dem/bin/
      - name: Archive compiled artifact
        uses: actions/upload-artifact@v3
        with:
          name: soot-dem-linux-gnu-x86_64
          path: |
            dist
